name: "sonar_cloud_scan_github_actions"
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      